jwt:
  secret: 'jwt1234'
  expiresIn: 3600

kakao:
  clientID: '796fc24ede3f528012f5ffb2d6a99f06'
#  callbackURL: 'http://localhost:3000/auth/kakao/redirect'
  callbackURL: 'http://localhost:3000/auth/kakaoCallback'